# Generated by Django 6.0.7 on 2026-07-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('genre', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
